language: c

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit

before_install:
  - sudo apt-get update
  - bash .travis/setup_lua.sh
  - luarocks install luasec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu --local
  - luarocks path > paths
  - echo 'PATH=$PATH:~/.luarocks/bin' >> paths
  - . paths

install:
  - luarocks make --local

script:
  # install rocks
  - luarocks install penlight --local
  - luarocks install luaposix --local
  - luarocks install rapidjson --local
  # Lua
  - lua -l single-dir -e 'require "pl.utils"'
  # C
  - lua -l single-dir -e 'require "rapidjson"'
  # All in one package
  - lua -l single-dir -e 'require "posix.curses"'
  # remove installed rocks
  - luarocks remove penlight --local
  - luarocks remove luaposix --local
  - luarocks remove rapidjson --local
  # test loading
  - export LUA_PATH="single-dir-out/modules/?.lua;single-dir-out/modules/?/init.lua"
  - export LUA_CPATH="single-dir-out/modules/?.so"
  - lua -e 'require "pl.utils"'
  - lua -e 'require "rapidjson"'
  - lua -e 'require "posix.curses"'
