language: c

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit

before_install:
  - sudo apt-get update
  - bash .travis/setup_lua.sh
  - bash .travis/install_rocks.sh
  - luarocks path > paths
  - echo 'PATH=$PATH:~/.luarocks/bin' >> paths
  - . paths

install:
  - luarocks make --local

script:
  # Lua
  - lua -l single-dir -e 'require "pl.utils"'
  # C
  - lua -l single-dir -e 'require "rapidjson"'
  # All in one package
  - lua -l single-dir -e 'require "posix.curses"'
  # test loading
  - export LUA_PATH="modules/?.lua;modules/?/init.lua"
  - export LUA_CPATH="modules/?.so"
  - lua -e 'require "pl.utils"'
  - lua -e 'require "rapidjson"'
  - lua -e 'require "posix.curses"'
