version: 0.0.1.{build}-test

os:
- Windows Server 2012 R2

shallow_clone: true

environment:
  LUAROCKS_VER: 2.2.2
  matrix:
  - LUA_VER: 5.1.5
  - LUA_VER: 5.2.4
  - LUA_VER: 5.2.4
    NOCOMPAT: true
  - LUA_VER: 5.3.0
  - LUA_VER: 5.3.0
    NOCOMPAT: true
  - LJ_VER: 2.0.3
  - LJ_VER: 2.1

platform:
  - x86
  - x64

cache:
  - c:\lua -> appveyor.yml
  - c:\external -> appveyor.yml

init:
# Setup Lua development/build environment
# Make VS 2013 command line tools available
- call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %platform%

install:
# Setup Lua development/build environment
- call .appveyor\install.bat

build_script:
- luarocks make

test_script:
- cd %APPVEYOR_BUILD_FOLDER%
# install rocks
- luarocks install penlight
- luarocks install rapidjson
# make modules directory
- lua -l single-dir -e "require 'pl.utils'"
- lua -l single-dir -e "require 'rapidjson'"
# remove rocks
- luarocks remove penlight
- luarocks remove rapidjson
# check loading
- set LUA_PATH=single-dir-out/modules/?.lua;single-dir-out/modules/?/init.lua
- set LUA_CPATH=single-dir-out/modules/?.dll
- lua -e "require 'pl.utils'"
- lua -e "require 'rapidjson'"
